package label

// DeepCopyInto is an autogenerated deep copy function, copying the receiver, writing into out. in must be non-nil.
func (r *Requirement) DeepCopyInto(out *Requirement) {
	*out = *r
	if r.strValues != nil {
		in, out := &r.strValues, &out.strValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deep copy function, copying the receiver, creating a new Requirement.
func (r *Requirement) DeepCopy() *Requirement {
	if r == nil {
		return nil
	}
	out := new(Requirement)
	r.DeepCopyInto(out)
	return out
}
